#!/usr/bin/env sh
set -eu

echo "pre-commit: cargo fmt --all -- --check"
cargo fmt --all -- --check

echo "pre-commit: cargo clippy --locked --workspace --all-targets -- -D warnings"
cargo clippy --locked --workspace --all-targets -- -D warnings
