use pacquet_npmrc::NodeLinker;
use std::{fs, io, path::Path};

pub(crate) fn write_pnp_manifest_if_needed(
    node_linker: &NodeLinker,
    lockfile_dir: &Path,
) -> io::Result<()> {
    if !matches!(node_linker, NodeLinker::Pnp) {
        return Ok(());
    }

    fs::write(lockfile_dir.join(".pnp.cjs"), pnp_manifest_contents())
}

fn pnp_manifest_contents() -> &'static str {
    "'use strict';\n\n// pnpm-compatible placeholder generated by pacquet.\nmodule.exports = {\n  setup() {},\n};\n"
}

#[cfg(test)]
mod tests {
    use super::write_pnp_manifest_if_needed;
    use pacquet_npmrc::NodeLinker;
    use std::fs;

    #[test]
    fn writes_pnp_manifest_when_pnp_is_enabled() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_pnp_manifest_if_needed(&NodeLinker::Pnp, dir.path()).expect("write pnp manifest");

        let content = fs::read_to_string(dir.path().join(".pnp.cjs")).expect("read pnp manifest");
        assert!(content.contains("module.exports"));
        assert!(content.contains("setup() {}"));
    }

    #[test]
    fn does_not_write_pnp_manifest_for_non_pnp_linkers() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_pnp_manifest_if_needed(&NodeLinker::Isolated, dir.path()).expect("skip pnp manifest");

        assert!(!dir.path().join(".pnp.cjs").exists());
    }
}
